const assert=require('node:assert/strict');const {chromium}=require('playwright-core');
(async()=>{const browser=await chromium.launch({headless:true});try{const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.argv[2]);await page.waitForFunction(()=>window.__locks);const mode=process.argv[3]||'base';const state=()=>page.evaluate(()=>window.__locks.state());const click=id=>page.locator(id).click();
assert.equal(await page.locator('h1').textContent(),'Pocket Locks');assert.equal(await page.locator('#canal').getAttribute('role'),'img');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
const before=await state();await click('#gate-0-high');assert.equal(await page.locator('#status').textContent(),'Match water levels before opening this gate.');assert.deepEqual(await state(),before);
for(const id of ['#gate-0-low','#sail-forward','#gate-0-low','#water-0-high','#gate-0-high','#sail-forward'])await click(id);
assert.equal((await state()).won,true);assert.equal(await page.locator('#status').textContent(),'Moored! You brought the boat home in 6 moves.');await click('#undo');assert.equal((await state()).boat,1);await click('#restart');assert.equal((await state()).moves,0);
if(mode==='levels'||mode==='budget'){
 await page.selectOption('#trip','downhill');for(const id of ['#gate-0-high','#sail-back','#gate-0-high','#water-0-low','#gate-0-low','#sail-back'])await click(id);assert.equal((await state()).won,true);
 await page.selectOption('#trip',mode==='budget'?'thirsty':'two-step');for(let i=0;i<2;i++)for(const id of [`#gate-${i}-low`,'#sail-forward',`#gate-${i}-low`,`#water-${i}-high`,`#gate-${i}-high`,'#sail-forward'])await click(id);assert.equal((await state()).moves,12);assert.equal((await state()).won,true);
}
if(mode==='budget'){assert.equal(await page.locator('#water-budget').textContent(),'Water tokens: 0 / 2');await click('#restart');assert.equal(await page.locator('#water-budget').textContent(),'Water tokens: 2 / 2');await click('#water-0-high');await click('#water-0-low');await click('#water-0-high');await click('#water-0-low');const before=await state();await click('#water-0-high');assert.deepEqual(await state(),before);assert.equal(await page.locator('#status').textContent(),'No water tokens left. Undo or restart.');await click('#undo');assert.equal((await state()).moves,3);await click('#undo');assert.equal((await state()).fills,1);}
for(const size of [{width:390,height:844},{width:1280,height:900}]){await page.setViewportSize(size);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);for(const button of await page.locator('button:visible').all()){await button.scrollIntoViewIfNeeded();const r=await button.boundingBox();assert.ok(r.height>=44);}}
assert.deepEqual(errors,[]);console.log(mode==='base'?'a little boat rises through a playable phone-sized lock':mode==='levels'?'three canal trips are playable uphill downhill and through two locks':'the thirsty hill spends water tokens and undo restores them');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
