const assert=require('node:assert/strict');const {chromium}=require('playwright-core');
const mode=process.argv[2],url=process.argv[3];
const rows={
 'two-hills-home':{name:'Two hills and home',description:'Climb both hills, then bring the boat back. Keep the water you leave behind.',spec:{reaches:[0,1,2],water:[0,1],start:0,target:0,budget:2,stops:[4,0]},moves:22,fills:2,path:'gate-0-low,sail-forward,gate-0-low,water-0-high,gate-0-high,sail-forward,gate-1-low,sail-forward,gate-1-low,water-1-high,gate-1-high,sail-forward,sail-back,gate-1-high,water-1-low,gate-1-low,sail-back,sail-back,gate-0-high,water-0-low,gate-0-low,sail-back'},
 'middle-errand':{name:'Middle errand',description:'Visit the middle reach, carry on to the top, then moor in the middle again.',spec:{reaches:[0,1,2],water:[0,1],start:0,target:2,budget:2,stops:[2,4,2]},moves:17,fills:2,path:'gate-0-low,sail-forward,gate-0-low,water-0-high,gate-0-high,sail-forward,gate-1-low,sail-forward,gate-1-low,water-1-high,gate-1-high,sail-forward,sail-back,gate-1-high,water-1-low,gate-1-low,sail-back'},
 'two-deliveries':{name:'Two deliveries',description:'Visit the middle reach, return to the beginning, then climb to the top. The first lock must lift you twice.',spec:{reaches:[0,1,2],water:[0,1],start:0,target:4,budget:3,stops:[2,0,4]},moves:22,fills:3,path:'gate-0-low,sail-forward,gate-0-low,water-0-high,gate-0-high,sail-forward,sail-back,gate-0-high,water-0-low,gate-0-low,sail-back,sail-forward,gate-0-low,water-0-high,gate-0-high,sail-forward,gate-1-low,sail-forward,gate-1-low,water-1-high,gate-1-high,sail-forward'}
};
const groups={ 'Learn the gates':['uphill','downhill','chamber-home','two-step','thirsty'],'Water already waiting':['ready-water','high-chamber-home','last-chamber-home'],'Longer crossings':['long-descent','middle-mooring','long-climb','long-way-home'],'Visit and return':['there-and-back','chamber-visit','two-hills-home','middle-errand','two-deliveries']};
(async()=>{if(!url)throw Error('URL required');const {trips}=await import('../site/trips.mjs');if(mode!=='groups'){const row=rows[mode];assert(row);const trip=trips.find(t=>t.id===mode);assert.deepEqual(trip,{id:mode,name:row.name,description:row.description,spec:row.spec});}
const b=await chromium.launch({headless:true});try{for(const width of [390,1280]){const p=await b.newPage({viewport:{width,height:900}});assert.equal((await p.goto(url)).status(),200);const state=()=>p.evaluate(()=>__locks.state());if(mode==='groups'){assert.deepEqual(await p.locator('#trip optgroup').evaluateAll(gs=>Object.fromEntries(gs.map(g=>[g.label,[...g.querySelectorAll('option')].map(o=>o.value)]))),groups);assert.equal(await p.locator('#trip > option').count(),0);assert.equal(await p.inputValue('#trip'),'uphill');for(const id of ['downhill','ready-water','long-climb','two-deliveries']){await p.selectOption('#trip',id);assert.equal((await state()).boat,trips.find(t=>t.id===id).spec.start);assert.equal((await state()).moves,0);} }else{const row=rows[mode];await p.selectOption('#trip',mode);assert.equal(await p.textContent('#trip-description'),row.description);let before;for(const id of row.path.split(',')){before=await state();await p.click('#'+id);const after=await state();assert.equal(after.moves,before.moves+1);if(after.stopIndex>before.stopIndex){assert.equal(after.won,false);assert.equal(after.target,row.spec.stops[after.stopIndex]);assert.equal(await p.textContent('#journey-stage'),`Stop ${after.stopIndex+1} of ${row.spec.stops.length} · Reach ${after.target/2+1}`);}}let s=await state();assert.equal(s.moves,row.moves);assert.equal(s.fills,row.fills);assert.equal(s.boat,row.spec.target);assert.equal(s.won,true);assert.equal(await p.textContent('#journey-stage'),'All stops visited.');await p.click('#undo');assert.deepEqual(await state(),before);await p.click('#restart');s=await state();assert.deepEqual(s.stops,row.spec.stops);assert.equal(s.stopIndex,0);assert.equal(s.moves,0);assert.equal(s.fills,0);assert.equal(s.won,false);}assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.close();}
console.log(mode==='groups'?'canal trips are grouped without losing a route':`${mode} completes its ordered route and restores history`);}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
